rmsshkey: Implement interactive mode.

diff --git a/autoload/rmsshkey b/autoload/rmsshkey
--- a/autoload/rmsshkey
+++ b/autoload/rmsshkey
@@ -19,12 +19,20 @@ function _rmsshkey_checkcmds {
 	return 0
 }
 
-# Returns 1 if dry-run mode is enabled, 0 otherwise.
+# Returns 0 if dry-run mode is enabled, 1 otherwise.
 function _rmsshkey_is_dryrun {
-	if [[ -n "${(k)_rmsshkeys_opts[-n]}" ]]; then
-		return 1
+	if [[ -n "${(k)_rmsshkey_opts[-n]}" ]]; then
+		return 0
 	fi
-	return 0
+	return 1
+}
+
+# Returns 0 if interactive mode is enabled, 1 otherwise.
+function _rmsshkey_is_interactive {
+	if [[ -n "${(k)_rmsshkey_opts[-i]}" ]]; then
+		return 0
+	fi
+	return 1
 }
 
 # Gets the addresses of a given RRType and hostname
@@ -57,6 +65,39 @@ function _rmsshkey_keyexists {
 	return $?
 }
 
+# If in interactive mode, asks if the key should be deleted, otherwise
+# returns 0.
+function _rmsshkey_should_remove {
+	local -r addr="$1"
+	if ! _rmsshkey_is_interactive; then
+		return 0
+	fi
+
+	local PROMPT3="Remove key for ${addr}?: "
+	local REPLY
+	local answer
+
+	echo ""
+	select answer in Yes No; do
+		if [[ -z "${answer}" ]]; then
+			answer="${REPLY}"
+		fi
+		case "${answer}" in
+			[Yy]es|[Yy])
+				return 0
+				;;
+			[Nn]o|[Nn])
+				return 1
+				;;
+			*)
+				echo "Invalid choice."
+				;;
+		esac
+	done
+
+	return 0
+}
+
 # Removes a key via "ssh-keygen -R" after checking that the key actually
 # exists to begin with. Returns the exit status of the last ssh-keygen
 # invocation.
@@ -65,7 +106,11 @@ function _rmsshkey_removekey {
 	for addr ($@) {
 		if ! _rmsshkey_keyexists "${addr}"; then
 			_rmsshkey_verbose "No key for ${addr}"
-			continue;
+			continue
+		fi
+
+		if ! _rmsshkey_should_remove "${addr}"; then
+			continue
 		fi
 
 		_rmsshkey_verbose "Removing ssh-key for ${addr}"
